name: 'My JavaScript Action'
description: 'An action that greets a user by name'
inputs:
  name:
    description: 'Name of the person to greet'
    required: true
outputs:
  greeting:
    description: 'The greeting message'

runs:
  using: "node16"
  main: "dist/index.js"  # Make sure this points to the built file
